
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: uvicorn IRGPT.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
volumes:
  postgres_data: